version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alimal-digital-system
    container_name: alimal_digital_system_app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=alimal-digital
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/alimal-digital-system
    ports:
      - "9000:9000"
    networks:
      - alimal-digital-network

  db:
    image: mysql:8.0
    container_name: alimal_digital_system_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alimal-digital
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - alimal-digital-network
    ports:
      - "3307:3306"

  nginx:
    image: nginx:alpine
    container_name: alimal_digital_system_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/alimal-digital-system
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use your nginx.conf directly
    depends_on:
      - app
    networks:
      - alimal-digital-network

networks:
  alimal-digital-network:
    driver: bridge

volumes:
  dbdata:
    driver: local